version: '2.13.0'

services:
  webserver:
    build: .
    ports:
      - 8090:80
    networks:
      - connwebserver
    volumes:
      - dev:/var/www/
  serverdb:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: seypre2023
    ports:
      - 5432:5432
    networks:
      - connwebserver
      - connserverdb
    volumes:
      - pgdata:/pgdata/
  servercache:
    image: redis:7.0.7-alpine
    ports:
      - 6379:6379
    networks:
      - connserverdb
    volumes:
      - redisdata:/redis/data
  clientedb:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=jacal2211@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80
    networks:
      - connserverdb

volumes:
  pgdata:
  dev:
  redisdata:
  
networks:
  connwebserver:
    driver: bridge
  connserverdb:
    driver: bridge

  